updates.pin = [
  { groupId = "org.scala-lang", artifactId = "scala-library", version = "2.12." }
  # we have too many build plugins that need sbt 1.x
  { groupId = "org.scala-sbt", artifactId = "sbt", version = "1." }
]
