<ul class="md-nav__list md-nav__links">
      <li class="md-nav__item"><a href="https://apache.org"><i class="md-icon">link</i> Apache Software Foundation</a></li>
      <li class="md-nav__item"><a href="https://apache.org/licenses/"><i class="md-icon">link</i>&nbsp;License</a></li>
      <li class="md-nav__item"><a href="https://apache.org/security/"><i class="md-icon">link</i>&nbsp;Security</a></li>
      <li class="md-nav__item"><a href="https://privacy.apache.org/policies/privacy-policy-public.html"><i class="md-icon">link</i>&nbsp;Privacy</a></li>
      <li class="md-nav__item"><a href="https://www.apache.org/events/current-event.html"><i class="md-icon">link</i>&nbsp;Events</a></li>
      <li class="md-nav__item"><a href="https://www.apache.org/foundation/sponsorship.html"><i class="md-icon">link</i>&nbsp;Donate</a></li>
      <li class="md-nav__item"><a href="https://www.apache.org/foundation/thanks.html"><i class="md-icon">link</i>&nbsp;Thanks</a></li>
</ul>
